project_id = "nmlkqyhkygdajqaffzny"

[functions.diagnostic-chat]
verify_jwt = false

[functions.generate-audit-report]
verify_jwt = false

[functions.generate-quote-pdf]
verify_jwt = false

[functions.workflow-hook]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-proposal-email]
verify_jwt = false

[functions.generate-specifications]
verify_jwt = false

[functions.generate-admin-proposals]
verify_jwt = false

[functions.chat-faq]
verify_jwt = false

[functions.generate-preReception-report]
verify_jwt = false

[functions.generate-demo-audit-json]
verify_jwt = false
