project_id = "nmlkqyhkygdajqaffzny"

[functions.diagnostic-chat]
verify_jwt = false

[functions.generate-audit-report]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.generate-specifications]
verify_jwt = false

[functions.generate-admin-proposals]
verify_jwt = false
